### PR TITLE
Changes to create secret from kustomize

### PR DESCRIPTION
**Pull request by ambiknai**
This PR incorporates changes to create secret from kustomize.
README update is only related to above change. 
All other READMe changes will be taken as  a separate PR

### CODE REVIEW

**Comment by ambiknai** [comment]
```
# bash deploy/kubernetes/driver/kubernetes/deploy-vpc-block-driver.sh stage gen2
This will install 'stage' version of vpc csi driver for 'gen2' !
serviceaccount/ibm-vpc-block-controller-sa configured
serviceaccount/ibm-vpc-block-node-sa configured
clusterrole.rbac.authorization.k8s.io/vpc-block-driver-registrar-role unchanged
clusterrole.rbac.authorization.k8s.io/vpc-block-external-attacher-role unchanged
clusterrole.rbac.authorization.k8s.io/vpc-block-external-resizer-role unchanged
clusterrole.rbac.authorization.k8s.io/vpc-block-provisioner-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-driver-registrar-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-external-attacher-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-external-resizer-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-provisioner-binding unchanged
configmap/ibm-vpc-block-csi-configmap unchanged
secret/storage-secret-store unchanged
statefulset.apps/ibm-vpc-block-csi-controller configured
daemonset.apps/ibm-vpc-block-csi-node unchanged
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
csidriver.storage.k8s.io/vpc.block.csi.ibm.io unchanged

```

**Comment by ambiknai** [comment]
```
bash deploy/kubernetes/driver/kubernetes/deploy-vpc-block-driver.sh stage
This will install 'stage' version of vpc csi driver!
serviceaccount/ibm-vpc-block-controller-sa created
serviceaccount/ibm-vpc-block-node-sa created
clusterrole.rbac.authorization.k8s.io/vpc-block-driver-registrar-role created
clusterrole.rbac.authorization.k8s.io/vpc-block-external-attacher-role created
clusterrole.rbac.authorization.k8s.io/vpc-block-external-resizer-role created
clusterrole.rbac.authorization.k8s.io/vpc-block-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-driver-registrar-binding created
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-external-attacher-binding created
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-external-resizer-binding created
clusterrolebinding.rbac.authorization.k8s.io/vpc-block-provisioner-binding created
configmap/ibm-vpc-block-csi-configmap created
secret/storage-secret-store created
statefulset.apps/ibm-vpc-block-csi-controller created
daemonset.apps/ibm-vpc-block-csi-node created
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
csidriver.storage.k8s.io/vpc.block.csi.ibm.io created
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pods
NAME                                         READY   STATUS    RESTARTS   AGE
testpodcsi-block-pvc-four-6b855b8cbf-hxwf6   1/1     Running   0          12m
testpodcsi-block-pvc-one-789769f4c7-lp7md    1/1     Running   0          2d2h
testpodrwo-749774548d-nbjgl                  1/1     Running   0          15d
web-0                                        1/1     Running   0          14d
web-1                                        1/1     Running   0          14d
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc delete pod testpodcsi-block-pvc-four-6b855b8cbf-hxwf6 
pod "testpodcsi-block-pvc-four-6b855b8cbf-hxwf6" deleted
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-four   Bound    pvc-40e9c8d1-e5e2-4ea5-84b6-7ccd247a97a8   10Gi       RWO            ibmc-vpc-block-5iops-tier   25m
csi-block-pvc-good   Bound    pvc-f681406a-7fa0-4451-b15f-b30e37ff48f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   19d
csi-block-pvc-one    Bound    pvc-0185e150-b82f-4ee6-b2d3-9a80e3a72e42   10Gi       RWO            ibmc-vpc-block-5iops-tier   2d2h
www-web-0            Bound    pvc-89a01401-3318-437e-9798-79d29e7498cb   25Gi       RWO            ibmc-vpc-block-5iops-tier   14d
www-web-1            Bound    pvc-95571230-9ebb-47a9-835a-dfbadb413662   25Gi       RWO            ibmc-vpc-block-5iops-tier   14d
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc delete pvc csi-block-pvc-four 
persistentvolumeclaim "csi-block-pvc-four" deleted
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc create -f examples/kubernetes/
README.md                 pvc-with-tags.yaml        raw-block-pvc.yaml        validPOD.yaml             volume-tags-secret.yaml   
invalidPVC.yaml           raw-block-pod.yaml        storageclass-secret.yaml  validPVC.yaml             
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc create -f examples/kubernetes/
README.md                 pvc-with-tags.yaml        raw-block-pvc.yaml        validPOD.yaml             volume-tags-secret.yaml   
invalidPVC.yaml           raw-block-pod.yaml        storageclass-secret.yaml  validPVC.yaml             
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc create -f examples/kubernetes/
README.md                 pvc-with-tags.yaml        raw-block-pvc.yaml        validPOD.yaml             volume-tags-secret.yaml   
invalidPVC.yaml           raw-block-pod.yaml        storageclass-secret.yaml  validPVC.yaml             
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc create -f examples/kubernetes/validPVC.yaml
persistentvolumeclaim/csi-block-pvc-four created
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pvc
NAME                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-four   Pending                                                                        ibmc-vpc-block-5iops-tier   24s
csi-block-pvc-good   Bound     pvc-f681406a-7fa0-4451-b15f-b30e37ff48f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   19d
csi-block-pvc-one    Bound     pvc-0185e150-b82f-4ee6-b2d3-9a80e3a72e42   10Gi       RWO            ibmc-vpc-block-5iops-tier   2d2h
www-web-0            Bound     pvc-89a01401-3318-437e-9798-79d29e7498cb   25Gi       RWO            ibmc-vpc-block-5iops-tier   14d
www-web-1            Bound     pvc-95571230-9ebb-47a9-835a-dfbadb413662   25Gi       RWO            ibmc-vpc-block-5iops-tier   14d
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-four   Bound    pvc-cf1aa85f-f50a-4a3e-852c-76e1c44cc837   10Gi       RWO            ibmc-vpc-block-5iops-tier   39s
csi-block-pvc-good   Bound    pvc-f681406a-7fa0-4451-b15f-b30e37ff48f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   19d
csi-block-pvc-one    Bound    pvc-0185e150-b82f-4ee6-b2d3-9a80e3a72e42   10Gi       RWO            ibmc-vpc-block-5iops-tier   2d2h
www-web-0            Bound    pvc-89a01401-3318-437e-9798-79d29e7498cb   25Gi       RWO            ibmc-vpc-block-5iops-tier   14d
www-web-1            Bound    pvc-95571230-9ebb-47a9-835a-dfbadb413662   25Gi       RWO            ibmc-vpc-block-5iops-tier   14d
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc create -f examples/kubernetes/
README.md                 pvc-with-tags.yaml        raw-block-pvc.yaml        validPOD.yaml             volume-tags-secret.yaml   
invalidPVC.yaml           raw-block-pod.yaml        storageclass-secret.yaml  validPVC.yaml             
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc create -f examples/kubernetes/validPOD.yaml 
deployment.apps/testpodcsi-block-pvc-four created
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pods -n kube-system | grep block
ibm-vpc-block-csi-controller-0                 5/5     Running   0          4m5s
ibm-vpc-block-csi-node-89zdv                   4/4     Running   0          4m4s
ibm-vpc-block-csi-node-xhbp5                   4/4     Running   0          4m4s
ibm-vpc-block-csi-node-zh4zg                   4/4     Running   0          4m4s
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc describe pod -n kube-system ibm-vpc-block-csi-controller-0 
Name:               ibm-vpc-block-csi-controller-0
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               sat-ocp-workernode03/10.242.128.5
Start Time:         Wed, 22 Sep 2021 04:15:26 -0700
Labels:             app=ibm-vpc-block-csi-driver
                    controller-revision-hash=ibm-vpc-block-csi-controller-bd46d85c6
                    statefulset.kubernetes.io/pod-name=ibm-vpc-block-csi-controller-0
Annotations:        cni.projectcalico.org/podIP: 172.30.105.118/32
                    cni.projectcalico.org/podIPs: 172.30.105.118/32
                    k8s.v1.cni.cncf.io/network-status:
                      [{
                          "name": "",
                          "ips": [
                              "172.30.105.118"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "",
                          "ips": [
                              "172.30.105.118"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    prometheus.io/path: /metrics
                    prometheus.io/port: 9080
                    prometheus.io/scrape: true
Status:             Running
IP:                 172.30.105.118
Controlled By:      StatefulSet/ibm-vpc-block-csi-controller
Containers:
  csi-provisioner:
    Container ID:  cri-o://84938b6f9b2227e50a69f18e95bbbe71fe8a5c85ebcdfeed266729e1814f72ce
    Image:         k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
    Image ID:      k8s.gcr.io/sig-storage/csi-provisioner@sha256:04c55b93a032ad8075cae540d60fc740a72c31006590dbdb61ad4ab9813959d0
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=$(ADDRESS)
      --timeout=600s
      --feature-gates=Topology=true
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:30 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      ADDRESS:  /csi/csi.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-controller-sa-token-z4px2 (ro)
  csi-attacher:
    Container ID:  cri-o://ce666da1422c5a22323ba32a548d85efad0477790f4123f7d6846782ca00249b
    Image:         k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
    Image ID:      k8s.gcr.io/sig-storage/csi-attacher@sha256:60ab9b3e6a030d3038c87c0d6bca2930f58d1d72823e6a4af09767dc83b696a2
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=/csi/csi.sock
      --timeout=900s
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:34 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-controller-sa-token-z4px2 (ro)
  liveness-probe:
    Container ID:  cri-o://aaa5fa95bcac71248e349f280cb1bd5c1d92eeaafb3481bf692ba5777b26bed7
    Image:         k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
    Image ID:      k8s.gcr.io/sig-storage/livenessprobe@sha256:1b7c978a792a8fa4e96244e8059bd71bb49b07e2e5a897fb0c867bdc6db20d5d
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=/csi/csi.sock
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:38 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:        5m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-controller-sa-token-z4px2 (ro)
  iks-vpc-block-driver:
    Container ID:  cri-o://1da23b7fcb2fb73128811a26eb417818b0aec282bb287a2419a9fe3695d67643
    Image:         ambikanair/ibm-vpc-block-csi-driver:nilfix
    Image ID:      docker.io/ambikanair/ibm-vpc-block-csi-driver@sha256:618799307d2b0dd3a0ea52ef8a83dacc15e681d2d6becc4798006bf58e01471e
    Port:          9808/TCP
    Host Port:     0/TCP
    Args:
      --v=5
      --endpoint=$(CSI_ENDPOINT)
      --lock_enabled=false
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:39 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
      cpu:     50m
      memory:  100Mi
    Liveness:  http-get http://:healthz/healthz delay=10s timeout=3s period=10s #success=1 #failure=5
    Environment Variables from:
      ibm-vpc-block-csi-configmap  ConfigMap  Optional: false
    Environment:
      POD_NAME:       ibm-vpc-block-csi-controller-0 (v1:metadata.name)
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /csi from socket-dir (rw)
      /etc/storage_ibmc from customer-auth (ro)
      /etc/storage_ibmc/cluster_info from cluster-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-controller-sa-token-z4px2 (ro)
  csi-resizer:
    Container ID:  cri-o://dfcc41fdd4e1b6e562fcaf5007fca70e2d5fe2b870a0855602304a391e002a43
    Image:         k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
    Image ID:      k8s.gcr.io/sig-storage/csi-resizer@sha256:36c31f7e1f433c9634d24f876353e8646246d81a03c4e351202c2644daff1620
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=$(ADDRESS)
      --timeout=600s
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:42 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      ADDRESS:  /csi/csi.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-controller-sa-token-z4px2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  socket-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  customer-auth:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  storage-secret-store
    Optional:    false
  cluster-info:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cluster-info
    Optional:  false
  ibm-vpc-block-controller-sa-token-z4px2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ibm-vpc-block-controller-sa-token-z4px2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age    From                           Message
  ----    ------          ----   ----                           -------
  Normal  Scheduled       4m20s  default-scheduler              Successfully assigned kube-system/ibm-vpc-block-csi-controller-0 to sat-ocp-workernode03
  Normal  AddedInterface  4m19s  multus                         Add eth0 [172.30.105.118/32]
  Normal  Pulling         4m19s  kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2"
  Normal  Pulled          4m16s  kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2" in 2.639345032s
  Normal  Created         4m16s  kubelet, sat-ocp-workernode03  Created container csi-provisioner
  Normal  Started         4m16s  kubelet, sat-ocp-workernode03  Started container csi-provisioner
  Normal  Pulling         4m16s  kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/csi-attacher:v3.2.1"
  Normal  Pulled          4m13s  kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/csi-attacher:v3.2.1" in 3.298816731s
  Normal  Created         4m12s  kubelet, sat-ocp-workernode03  Created container csi-attacher
  Normal  Started         4m12s  kubelet, sat-ocp-workernode03  Started container csi-attacher
  Normal  Pulling         4m12s  kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/livenessprobe:v2.3.0"
  Normal  Pulled          4m9s   kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/livenessprobe:v2.3.0" in 2.881873273s
  Normal  Created         4m8s   kubelet, sat-ocp-workernode03  Created container liveness-probe
  Normal  Started         4m8s   kubelet, sat-ocp-workernode03  Started container liveness-probe
  Normal  Pulling         4m8s   kubelet, sat-ocp-workernode03  Pulling image "ambikanair/ibm-vpc-block-csi-driver:nilfix"
  Normal  Pulled          4m7s   kubelet, sat-ocp-workernode03  Successfully pulled image "ambikanair/ibm-vpc-block-csi-driver:nilfix" in 1.357777929s
  Normal  Created         4m7s   kubelet, sat-ocp-workernode03  Created container iks-vpc-block-driver
  Normal  Started         4m7s   kubelet, sat-ocp-workernode03  Started container iks-vpc-block-driver
  Normal  Pulling         4m7s   kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/csi-resizer:v1.2.0"
  Normal  Pulled          4m4s   kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/csi-resizer:v1.2.0" in 2.556516408s
  Normal  Created         4m4s   kubelet, sat-ocp-workernode03  Created container csi-resizer
  Normal  Started         4m4s   kubelet, sat-ocp-workernode03  Started container csi-resizer
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc describe pod -n kube-system ibm-vpc-block-csi-node-89zdv
Name:               ibm-vpc-block-csi-node-89zdv
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               sat-ocp-workernode03/10.242.128.5
Start Time:         Wed, 22 Sep 2021 04:15:27 -0700
Labels:             app=ibm-vpc-block-csi-driver
                    controller-revision-hash=565bf79c44
                    pod-template-generation=1
Annotations:        cni.projectcalico.org/podIP: 172.30.105.90/32
                    cni.projectcalico.org/podIPs: 172.30.105.90/32
                    k8s.v1.cni.cncf.io/network-status:
                      [{
                          "name": "",
                          "ips": [
                              "172.30.105.90"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "",
                          "ips": [
                              "172.30.105.90"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    prometheus.io/path: /metrics
                    prometheus.io/port: 9080
                    prometheus.io/scrape: true
Status:             Running
IP:                 172.30.105.90
Controlled By:      DaemonSet/ibm-vpc-block-csi-node
Containers:
  iks-vpc-block-node-driver:
    Container ID:  cri-o://d40911c5d6421f373b4c7dd50bfb9a79b3a0c85feeb80e4e03d6fa31bd3d0b91
    Image:         ambikanair/ibm-vpc-block-csi-driver:nilfix
    Image ID:      docker.io/ambikanair/ibm-vpc-block-csi-driver@sha256:618799307d2b0dd3a0ea52ef8a83dacc15e681d2d6becc4798006bf58e01471e
    Port:          9808/TCP
    Host Port:     0/TCP
    Args:
      --v=5
      --endpoint=unix:/csi/csi.sock
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:31 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  250Mi
    Requests:
      cpu:     20m
      memory:  50Mi
    Liveness:  http-get http://:healthz/healthz delay=10s timeout=3s period=10s #success=1 #failure=5
    Environment Variables from:
      ibm-vpc-block-csi-configmap  ConfigMap  Optional: false
    Environment:
      KUBE_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /csi from plugin-dir (rw)
      /dev from device-dir (rw)
      /etc/storage_ibmc from customer-auth (ro)
      /etc/storage_ibmc/cluster_info from cluster-info (ro)
      /etc/udev from etcudevpath (rw)
      /lib/udev from libudevpath (rw)
      /run/udev from runudevpath (rw)
      /sys from syspath (rw)
      /var/data/kubelet from kubelet-data-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-node-sa-token-9hqjm (ro)
  csi-driver-registrar:
    Container ID:  cri-o://bc46f5b07478a3d768bf5523f7e6fc00ca102e18d93b72c5d3f0ddee66250906
    Image:         k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
    Image ID:      k8s.gcr.io/sig-storage/csi-node-driver-registrar@sha256:2dee3fe5fe861bb66c3a4ac51114f3447a4cd35870e0f2e2b558c7a400d89589
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=$(ADDRESS)
      --kubelet-registration-path=$(DRIVER_REGISTRATION_SOCK)
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:35 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      ADDRESS:                   /csi/csi.sock
      DRIVER_REGISTRATION_SOCK:  /var/lib/kubelet/csi-plugins/vpc.block.csi.ibm.io/csi.sock
      KUBE_NODE_NAME:             (v1:spec.nodeName)
    Mounts:
      /csi from plugin-dir (rw)
      /registration from registration-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-node-sa-token-9hqjm (ro)
  liveness-probe:
    Container ID:  cri-o://3108cd00f98c59152364753e24ee1ca8a1a0cd840a9f566cbad129b4d810ae22
    Image:         k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
    Image ID:      k8s.gcr.io/sig-storage/livenessprobe@sha256:1b7c978a792a8fa4e96244e8059bd71bb49b07e2e5a897fb0c867bdc6db20d5d
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=/csi/csi.sock
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:38 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:        5m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /csi from plugin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-node-sa-token-9hqjm (ro)
  csi-resizer:
    Container ID:   cri-o://62c9c45f81b144cfec61d9bd9b6b83a85da7ae032d8383dda6c3442cc51f46e4
    Image:          k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
    Image ID:       k8s.gcr.io/sig-storage/csi-resizer@sha256:36c31f7e1f433c9634d24f876353e8646246d81a03c4e351202c2644daff1620
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 22 Sep 2021 04:15:41 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-vpc-block-node-sa-token-9hqjm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  registration-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins_registry/
    HostPathType:  Directory
  kubelet-data-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/data/kubelet
    HostPathType:  Directory
  plugin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/csi-plugins/vpc.block.csi.ibm.io/
    HostPathType:  DirectoryOrCreate
  device-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  etcudevpath:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/udev
    HostPathType:  Directory
  runudevpath:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  Directory
  libudevpath:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/udev
    HostPathType:  Directory
  syspath:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  Directory
  customer-auth:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  storage-secret-store
    Optional:    false
  cluster-info:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cluster-info
    Optional:  false
  ibm-vpc-block-node-sa-token-9hqjm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ibm-vpc-block-node-sa-token-9hqjm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     
Events:
  Type    Reason          Age    From                           Message
  ----    ------          ----   ----                           -------
  Normal  Scheduled       4m31s  default-scheduler              Successfully assigned kube-system/ibm-vpc-block-csi-node-89zdv to sat-ocp-workernode03
  Normal  AddedInterface  4m30s  multus                         Add eth0 [172.30.105.90/32]
  Normal  Pulling         4m30s  kubelet, sat-ocp-workernode03  Pulling image "ambikanair/ibm-vpc-block-csi-driver:nilfix"
  Normal  Pulling         4m27s  kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0"
  Normal  Created         4m27s  kubelet, sat-ocp-workernode03  Created container iks-vpc-block-node-driver
  Normal  Started         4m27s  kubelet, sat-ocp-workernode03  Started container iks-vpc-block-node-driver
  Normal  Pulled          4m27s  kubelet, sat-ocp-workernode03  Successfully pulled image "ambikanair/ibm-vpc-block-csi-driver:nilfix" in 3.357759412s
  Normal  Pulling         4m23s  kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/livenessprobe:v2.3.0"
  Normal  Pulled          4m23s  kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0" in 3.660011404s
  Normal  Created         4m23s  kubelet, sat-ocp-workernode03  Created container csi-driver-registrar
  Normal  Started         4m23s  kubelet, sat-ocp-workernode03  Started container csi-driver-registrar
  Normal  Pulled          4m21s  kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/livenessprobe:v2.3.0" in 1.68966994s
  Normal  Created         4m20s  kubelet, sat-ocp-workernode03  Created container liveness-probe
  Normal  Started         4m20s  kubelet, sat-ocp-workernode03  Started container liveness-probe
  Normal  Pulling         4m20s  kubelet, sat-ocp-workernode03  Pulling image "k8s.gcr.io/sig-storage/csi-resizer:v1.2.0"
  Normal  Pulled          4m17s  kubelet, sat-ocp-workernode03  Successfully pulled image "k8s.gcr.io/sig-storage/csi-resizer:v1.2.0" in 3.389075831s
  Normal  Created         4m17s  kubelet, sat-ocp-workernode03  Created container csi-resizer
  Normal  Started         4m17s  kubelet, sat-ocp-workernode03  Started container csi-resizer
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# 
```

**Comment by ambiknai** [comment]
`Review comments`

```
remove gen1
update deploy-vpc-block-driver.sh  
config-map.yaml  test withput IKS_ENABLEd
in code make default values as false
update image “icr.io/ibm/ibm-vpc-block-csi-driver:v3.0.4”
sidecar image path change
g2_token_exchange_endpoint_url = "https://iam.bluemix.net"

readme -> supported riass region
readme-> vpc endpoints which supports gen2
```

**Review by arahamad — APPROVED** [review]
/lgtm

**Pull request merged**
