### PR TITLE
Run livenessprobe as nonroot - 5.1

### PR DESCRIPTION
**Pull request by prankulmahajan**
**This PR aims to do the following,**

1. In deployment set `runAsGroup` for all containers in nodeServer and controller. Currently, though the users are non-root, the group is still being used as root.
2. In deployment run `livenessprobe` sidecar as non-root user/group.

To achieve the 2nd point, had to change file permissions of CSI socket created by node server.

- Default permissions of csi socket inside node server -- (User 0, Group 0, Permissions 755) -- Only the root user has permissions to access the socket
- The socket file should have **read and write** permissions for access. i.e min access required is 600/660 depending on who is accessing the socket file

This PR changes the group of the csi socket from root to non-root(set 2121 in deployment configMap) and update permissions to 660. Setting "660" allows the root user and the non-root group to access the socket as expected.

### CODE REVIEW

**Comment by prankulmahajan** [comment]
### Environments to test:

- [x] Kubernetes service with Ubuntu 20 OS
- [ ] Kubernetes service with Ubuntu 24 OS
- [ ] Openshift with RHEL 8.9 OS
- [ ] Openshift with RHEL 9.6 OS
- [ ] Openshift with Coreos

### Test cases:
- New install
  - Resource status
  - PVC creation + Attachment + r/w
  - Expansion
  - Detachment + PVC deletion
- Patch install
  - Resource should be ready with existing PVC and attachment healthy
  - Create new attachement
  - Detachment + PVC deletion

**Comment by prankulmahajan** [comment]
## Test Results  (edit: after rebasing)

- [x] Setup -- Kubernetes
```
❯ kubectl get nodes
NAME          STATUS   ROLES    AGE    VERSION
10.240.0.37   Ready    <none>   114m   v1.30.4+IKS
10.240.0.38   Ready    <none>   118m   v1.30.4+IKS
```
- [x] Resource status
```
❯ kubectl get pods -n kube-system -o wide | grep block
ibm-vpc-block-csi-controller-cdfbf6469-4xv4s          7/7     Running   0              21s    172.17.96.6    10.240.0.37   <none>           <none>
ibm-vpc-block-csi-node-hhl5w                          4/4     Running   0              22s    172.17.66.22   10.240.0.38   <none>           <none>
ibm-vpc-block-csi-node-vsbj4                          4/4     Running   0              22s    172.17.96.5    10.240.0.37   <none>           <none>
```
- [x] Check if csi socket is retained after resource deletion -- socket got deleted 
- [x] Apply resources using custom image and check status + Exec into node and check csi socket permissions
```
❯ kubectl get pods -n kube-system -o wide | grep block
ibm-vpc-block-csi-controller-677b9855fd-7tcqd         7/7     Running   0             30s     172.17.109.31    10.240.0.85   <none>           <none>
ibm-vpc-block-csi-node-66mm9                          4/4     Running   0             31s     172.17.112.183   10.240.0.86   <none>           <none>
ibm-vpc-block-csi-node-jvtmq                          4/4     Running   0             31s     172.17.109.30    10.240.0.85   <none>           <none>


❯ runon 10.240.0.37 command bash
groups: cannot find name for group ID 11
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

(failed reverse-i-search)`cd ': cat /et^Cos-release
root@test-cr624av200pnjn76o2i0-iks130-default-000003e5:/# cd /var/lib/kubelet/plugins/vpc.block.csi.ibm.io/
root@test-cr624av200pnjn76o2i0-iks130-default-000003e5:/var/lib/kubelet/plugins/vpc.block.csi.ibm.io# ls
csi.sock
root@test-cr624av200pnjn76o2i0-iks130-default-000003e5:/var/lib/kubelet/plugins/vpc.block.csi.ibm.io# la -la
total 8
drwxr-xr-x 2 root root 4096 Sep  5 08:45 .
drwxr-x--- 5 root root 4096 Sep  5 08:43 ..
srw-rw---- 1 root 2121    0 Sep  5 08:45 csi.sock
root@test-cr624av200pnjn76o2i0-iks130-default-000003e5:/var/lib/kubelet/plugins/vpc.block.csi.ibm.io#

```
- [x] Create PVC and attach it to a pod
```
❯ kubectl get pvc
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                VOLUMEATTRIBUTESCLASS   AGE
my-pvc-block   Bound    pvc-ccab0bf0-37f5-483c-b6f8-88341ba680f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   <unset>                 56s
❯
❯
❯ kubectl get pods
NAME                                 READY   STATUS        RESTARTS   AGE
my-app-block-69956b9d94-67trr        1/1     Running       0          54s


❯ kubectl exec my-app-block-69956b9d94-67trr -it -- bahs
^C
❯ kubectl exec my-app-block-69956b9d94-67trr -it -- bash
bash-5.1# lsblk
bash: lsblk: command not found
bash-5.1# df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  97.3G      5.6G     87.4G   6% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     7.7G         0      7.7G   0% /sys/fs/cgroup
/dev/vdd                  9.7G     24.0K      9.7G   0% /myvolblock
/dev/vda2                97.3G      5.6G     87.4G   6% /etc/hosts
/dev/vda2                97.3G      5.6G     87.4G   6% /dev/termination-log
/dev/vda2                97.3G      5.6G     87.4G   6% /etc/hostname
/dev/vda2                97.3G      5.6G     87.4G   6% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    12.8G     16.0K     12.8G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     7.7G         0      7.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     7.7G         0      7.7G   0% /proc/scsi
tmpfs                     7.7G         0      7.7G   0% /sys/firmware
bash-5.1# cd myvolblock/
bash-5.1# touch test
bash-5.1# exit
exit
```
- [x] Expansion
```
❯ kubectl edit pvc my-pvc-block
persistentvolumeclaim/my-pvc-block edited

❯ kubectl get pvc -w
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                VOLUMEATTRIBUTESCLASS   AGE
my-pvc-block   Bound    pvc-ccab0bf0-37f5-483c-b6f8-88341ba680f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   <unset>                 6m5s
my-pvc-block   Bound    pvc-ccab0bf0-37f5-483c-b6f8-88341ba680f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   <unset>                 6m9s
my-pvc-block   Bound    pvc-ccab0bf0-37f5-483c-b6f8-88341ba680f8   20Gi       RWO            ibmc-vpc-block-5iops-tier   <unset>                 7m20s


```
- [x] Detach and delete PVC
```
❯ kubectl delete -f dep.yaml
deployment.apps "my-app-block" deleted
❯
❯
❯
❯ kubectl delete -f pvc.yaml
persistentvolumeclaim "my-pvc-block" deleted
❯
❯ kubectl get pods -o wide | grep my-app
❯
❯ kubectl get pvc
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                VOLUMEATTRIBUTESCLASS   AGE
csi-block-pvc   Bound    pvc-8a6de5ca-9750-49ff-ab8a-8272468a48f1   10Gi       RWO            ibmc-vpc-block-5iops-tier   <unset>                 22h
```
- [x] Delete csi resources 
```
❯ kubectl get pods -n kube-system -o wide | grep block
❯
```

**Review by arahamad — APPROVED** [review]
/lgtm

please verify also

**Review by sameshai — APPROVED** [review]
/lgtm

**Pull request merged**
