### PR TITLE
Code changes for removing unsupported parameters from code

### PR DESCRIPTION
**Pull request by ambiknai**
SizeRangeSupported and sizeIOPSRange were removed from SC as per  [this](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/61/files) PR.
We have to handle the same from code.

Removed parameters from SC as per #61 : **sizeIOPSRange** and **sizeRange** from Custom SC and  **sizeRange** from all other SCs

### CODE REVIEW

**Review by sameshai — APPROVED** [review]
/lgtm

**Review by meghnasiingh — APPROVED** [review]

**Review by sameshai — CHANGES_REQUESTED** [review]
do not merge

**Review by arahamad — APPROVED** [review]
/lgtm

**Comment by arahamad** [comment]
Please make sure IPI build should have updated storage classes

**Comment by ambiknai** [comment]
> @ambiknai Please make sure IPI build should have updated storage classes

https://github.com/openshift/ibm-vpc-block-csi-driver-operator/tree/master/assets/storageclass

**Comment by jsafrane** [comment]
This is a breaking change. If I had a cluster with a StorageClass with `SizeRangeSupported` and I update the driver, then I can't provision with that StorageClass, hence my cluster is broken.

StorageClass parameters are part of the driver API  (actually, it's the only API it has) and you need to keep it stable. You can deprecate a parameter and only after a generous time you can remove it. I haven't noticed a deprecation note in a previous release (and there is no CHANGELOG.md).

I am wondering if the Kubernetes deprecation policy applies here (this is a Kubernetes project, after all).

**Comment by arahamad** [comment]
> This is a breaking change. If I had a cluster with a StorageClass with `SizeRangeSupported` and I update the driver, then I can't provision with that StorageClass, hence my cluster is broken.
> 
> StorageClass parameters are part of the driver API (actually, it's the only API it has) and you need to keep it stable. You can deprecate a parameter and only after a generous time you can remove it. I haven't noticed a deprecation note in a previous release (and there is no CHANGELOG.md).
> 
> I am wondering if the Kubernetes deprecation policy applies here (this is a Kubernetes project, after all).

we discussed on this following would be the action for us
1- we will maintain  CHANGELOG.md file
2- Will follow k8s deprecation policy going forward https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**Pull request merged**
