### PR TITLE
Upgrade K8s dependencies to 1.26 

### PR DESCRIPTION
**Pull request by ambiknai**

### CODE REVIEW

**Review by sameshai — APPROVED** [review]
/lgtm

**Comment by ambiknai** [comment]
Testing is in progress. Please do not merge

**Comment by ambiknai** [comment]
```
  Normal  Pulling    96s   kubelet            Pulling image "icr.io/ext/sig-storage/csi-attacher:v3.5.0"
  Normal  Pulled     95s   kubelet            Successfully pulled image "icr.io/ext/sig-storage/csi-attacher:v3.5.0" in 315.24757ms (650.387615ms including waiting)
  Normal  Created    95s   kubelet            Created container csi-attacher
  Normal  Started    95s   kubelet            Started container csi-attacher
  Normal  Pulling    95s   kubelet            Pulling image "icr.io/ext/sig-storage/csi-resizer:v1.5.0"
  Normal  Pulled     94s   kubelet            Successfully pulled image "icr.io/ext/sig-storage/csi-resizer:v1.5.0" in 327.573198ms (327.596566ms including waiting)
  Normal  Created    94s   kubelet            Created container csi-resizer
  Normal  Started    94s   kubelet            Started container csi-resizer
  Normal  Pulled     94s   kubelet            Container image "icr.io/ext/sig-storage/livenessprobe:v2.6.0" already present on machine
  Normal  Created    94s   kubelet            Created container liveness-probe
  Normal  Started    94s   kubelet            Started container liveness-probe
  Normal  Pulling    94s   kubelet            Pulling image "gunakk777ibm/ibm-vpc-block-csi-driver:126"
  Normal  Pulled     94s   kubelet            Successfully pulled image "gunakk777ibm/ibm-vpc-block-csi-driver:126" in 326.981767ms (327.014384ms including waiting)
  Normal  Created    93s   kubelet            Created container iks-vpc-block-driver
  Normal  Started    93s   kubelet            Started container iks-vpc-block-driver
  Normal  Pulling    93s   kubelet            Pulling image "ambikanair/armada-storage-secret:latest"
  Normal  Pulled     93s   kubelet            Successfully pulled image "ambikanair/armada-storage-secret:latest" in 364.114663ms (364.148648ms including waiting)
ambikanair@Ambikas-MacBook-Pro demo % 
ambikanair@Ambikas-MacBook-Pro demo % 
ambikanair@Ambikas-MacBook-Pro demo % oc get pods
NAME                          READY   STATUS    RESTARTS   AGE
testcustom-84f4dd7557-ts495   1/1     Running   0          5d19h
ambikanair@Ambikas-MacBook-Pro demo % oc delete  -f pod.yaml 
deployment.apps "testcustom" deleted
ambikanair@Ambikas-MacBook-Pro demo % oc delete  -f pvc.yaml 
persistentvolumeclaim "csi-block-pvc-custom-one" deleted
ambikanair@Ambikas-MacBook-Pro demo % oc get volumesnapshots
NAME                   READYTOUSE   SOURCEPVC                  SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS            SNAPSHOTCONTENT   CREATIONTIME   AGE
snapshot-csi-block-6                csi-block-pvc-custom-one                                         ibmc-vpcblock-snapshot                                    5d20h
ambikanair@Ambikas-MacBook-Pro demo % oc delete -f volumeSnapshot.yaml 
volumesnapshot.snapshot.storage.k8s.io "snapshot-csi-block-6" deleted
ambikanair@Ambikas-MacBook-Pro demo % oc get pvc
No resources found in default namespace.
ambikanair@Ambikas-MacBook-Pro demo % oc create -f pvc.yaml 
persistentvolumeclaim/csi-block-pvc-custom-one created
ambikanair@Ambikas-MacBook-Pro demo % oc create -f pod.yaml 
deployment.apps/testcustom created
ambikanair@Ambikas-MacBook-Pro demo % oc get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-custom-one   Bound    pvc-86692e4c-1ff9-4cfc-a4c9-0a216df8f06f   10Gi       RWO            ibmc-vpc-block-5iops-tier   34s
ambikanair@Ambikas-MacBook-Pro demo % oc get pods
NAME                          READY   STATUS              RESTARTS   AGE
testcustom-84f4dd7557-5dfh2   0/1     ContainerCreating   0          28s
ambikanair@Ambikas-MacBook-Pro demo % oc get pods
NAME                          READY   STATUS    RESTARTS   AGE
testcustom-84f4dd7557-5dfh2   1/1     Running   0          76s
ambikanair@Ambikas-MacBook-Pro demo % oc edit pvc csi-block-pvc-custom-one 
persistentvolumeclaim/csi-block-pvc-custom-one edited
ambikanair@Ambikas-MacBook-Pro demo % oc get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-custom-one   Bound    pvc-86692e4c-1ff9-4cfc-a4c9-0a216df8f06f   20Gi       RWO            ibmc-vpc-block-5iops-tier   3m41s
ambikanair@Ambikas-MacBook-Pro demo % oc get nodes -o wide
NAME            STATUS   ROLES    AGE     VERSION        INTERNAL-IP     EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
10.240.0.11     Ready    <none>   5d23h   v1.23.16+IKS   10.240.0.11     10.240.0.11     Ubuntu 18.04.6 LTS   4.15.0-204-generic   containerd://1.6.15
10.240.128.12   Ready    <none>   5d23h   v1.23.16+IKS   10.240.128.12   10.240.128.12   Ubuntu 18.04.6 LTS   4.15.0-204-generic   containerd://1.6.15
10.240.64.13    Ready    <none>   5d23h   v1.23.16+IKS   10.240.64.13    10.240.64.13    Ubuntu 18.04.6 LTS   4.15.0-204-generic   containerd://1.6.15
ambikanair@Ambikas-MacBook-Pro demo %   
```
Testing completed

**Review by arahamad — APPROVED** [review]
/lgtm

Please verify tests as well

**Pull request merged**
