### PR TITLE
K8S upgrade to 28.6

### PR DESCRIPTION
**Pull request by GunaKKIBM**

### CODE REVIEW

**Review by ambiknai — COMMENTED** [review]
Could you post test results Guna

**Review by sameshai — COMMENTED** [review]
@GunaKKIBM lets build test image and test the one of the below versions

Before we test lets push the new CSI side car versions as part of addon under dev tag.So that we can test it once with all changes for one version. Rest we can test in stage.

4.11.52_openshift -- Grey area old IKS version

**Review by prankulmahajan — COMMENTED** [review]
/lgtm

**Comment by GunaKKIBM** [comment]
@ambiknai . Here are the test results:

```
% kubectl create -f pvc.yaml 
persistentvolumeclaim/my-pvc-block created

% kubectl create -f pod.yaml 
deployment.apps/my-deployment-blk created

% kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
custom-pod-58cc5b7794-tjqld          1/1     Running   0          10d
my-deployment-blk-65fbf9b4f4-mntnz   1/1     Running   0          61s

% kubectl exec -it my-deployment-blk-65fbf9b4f4-mntnz -- bash
root@my-deployment-blk-65fbf9b4f4-mntnz:/# 
root@my-deployment-blk-65fbf9b4f4-mntnz:/# cd /mount-path/
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# 
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   20G   73G  22% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/vda2        98G   20G   73G  22% /etc/hosts
/dev/vdd        9.7G   24K  9.7G   1% /mount-path
tmpfs            13G   24K   13G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /proc/scsi
tmpfs           7.9G     0  7.9G   0% /sys/firmware
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# echo "hi" > new.txt
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# 
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# 
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# cat new.txt 
hi
root@my-deployment-blk-65fbf9b4f4-mntnz:/mount-path# exit
exit

% kubectl create -f volumeSnapshot.yaml 
volumesnapshot.snapshot.storage.k8s.io/snapshot-csi-block created

% kubectl get volumesnapshots
NAME                 READYTOUSE   SOURCEPVC      SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS            SNAPSHOTCONTENT                                    CREATIONTIME   AGE
snapshot-csi-block   false        my-pvc-block                           10Gi          ibmc-vpcblock-snapshot   snapcontent-4da1aa83-eac7-49e7-a325-473d565c6e26   6s             8s

% kubectl get volumesnapshots
NAME                 READYTOUSE   SOURCEPVC      SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS            SNAPSHOTCONTENT                                    CREATIONTIME   AGE
snapshot-csi-block   false        my-pvc-block                           10Gi          ibmc-vpcblock-snapshot   snapcontent-4da1aa83-eac7-49e7-a325-473d565c6e26   10s            12s
% kubectl get volumesnapshots
NAME                 READYTOUSE   SOURCEPVC      SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS            SNAPSHOTCONTENT                                    CREATIONTIME   AGE
snapshot-csi-block   true         my-pvc-block                           10Gi          ibmc-vpcblock-snapshot   snapcontent-4da1aa83-eac7-49e7-a325-473d565c6e26   31s            33s

% kubectl create -f restorepvc.yaml 
persistentvolumeclaim/restore-pvc1 created

% kubectl get pvc
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-custom   Bound     pvc-835ebd7a-8d64-4d34-ad76-3887fd2d463d   10Gi       RWO            ibmc-vpc-block-5iops-tier   10d
csi-block-pvc-good     Pending                                                                        ibmc-vpc-block-5iops-tier   53m
my-pvc-block           Bound     pvc-856b54dd-6d6b-4f25-9987-28af648ce8f9   10Gi       RWO            ibmc-vpc-block-5iops-tier   2m48s
restore-pvc1           Pending                                                                        ibmc-vpc-block-5iops-tier   6s
% kubectl get pvc restore-pvc1 
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
restore-pvc1   Bound    pvc-07e7086b-4434-4e71-bd7b-bb646a9852af   11Gi       RWO            ibmc-vpc-block-5iops-tier   15s

% kubectl create -f restore-pod.yaml 
deployment.apps/restore-deployment created


gunakk@gunas-mbp ROKS-prod % kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
custom-pod-58cc5b7794-tjqld           1/1     Running   0          10d
my-deployment-blk-65fbf9b4f4-mntnz    1/1     Running   0          4m6s
restore-deployment-7d6f88b675-2pxpz   1/1     Running   0          66s
% kubectl exec -it my-deployment-blk-65fbf9b4f4-mntnz -- bash
root@my-deployment-blk-65fbf9b4f4-mntnz:/# 
root@my-deployment-blk-65fbf9b4f4-mntnz:/# cat /mount-path/
lost+found/ new.txt     
root@my-deployment-blk-65fbf9b4f4-mntnz:/# cat /mount-path/new.txt 
hi
root@my-deployment-blk-65fbf9b4f4-mntnz:/# 
root@my-deployment-blk-65fbf9b4f4-mntnz:/# exit
exit


% kubectl delete deploy my-deployment-blk  restore-deployment
deployment.apps "my-deployment-blk" deleted
deployment.apps "restore-deployment" deleted

% kubectl delete pvc my-pvc-block  restore-pvc1 
persistentvolumeclaim "my-pvc-block" deleted
persistentvolumeclaim "restore-pvc1" deleted

% kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS                REASON   AGE
pvc-835ebd7a-8d64-4d34-ad76-3887fd2d463d   10Gi       RWO            Delete           Bound    default/csi-block-pvc-custom   ibmc-vpc-block-5iops-tier            10d

% kubectl delete volumesnapshot snapshot-csi-block 
volumesnapshot.snapshot.storage.k8s.io "snapshot-csi-block" deleted

% kubectl get volumesnapshots                      
No resources found in default namespace.
```

**Review by arahamad — APPROVED** [review]
/lgtm

hope you verified the results

**Pull request merged**
