### PR TITLE
Issue #130: Using deployment for controller instead of statefulset

### PR DESCRIPTION
**Pull request by subhashmk**
## Issue
#130 

## Description of change
Using deployment for controller instead of statefulset

## Testing
**I don't know how to deploy complete ibm-vpc-block-driver chart, therefore tested changes directly on cluster.**

**Created similar deployment yaml using statefulset yaml and created controller deployment**

```
» kubectl delete sts ibm-vpc-block-csi-controller
statefulset.apps "ibm-vpc-block-csi-controller" deleted

» kubectl get sts
No resources found in kube-system namespace.

» kubectl get deploy
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
calico-kube-controllers              1/1     1            1           7d
calico-typha                         2/3     3            2           7d
coredns                              3/3     3            3           7d
coredns-autoscaler                   1/1     1            1           7d
dashboard-metrics-scraper            1/1     1            1           7d
ibm-vpc-block-csi-controller         1/1     1            1           24m
ingress-cluster-healthcheck          1/1     1            1           6d23h
kubernetes-dashboard                 1/1     1            1           7d
metrics-server                       2/2     2            2           7d
public-crchvepj92028h0ojro1f0-alb1   1/2     2            1           6d23h
public-crchvepj92028h0ojro1f0-alb2   1/2     2            1           6d23h
snapshot-controller                  3/3     3            3           7d

» kubectl get po -l app=ibm-vpc-block-csi-driver
NAME                                            READY   STATUS    RESTARTS   AGE
ibm-vpc-block-csi-controller-5955fbbdc8-t5lj2   7/7     Running   0          25m
ibm-vpc-block-csi-node-hfhcc                    4/4     Running   0          3d20h
ibm-vpc-block-csi-node-s7n7s                    4/4     Running   0          3d20h

» kubectl config set-context --current --namespace=default
Context "vpc-block-test-sushma/chvepj92028h0ojro1f0/admin" modified.

» kubectl create -f pvc.yaml
persistentvolumeclaim/my-pvc created

» kubectl get pvc
NAME     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                AGE
my-pvc   Pending                                      ibmc-vpc-block-5iops-tier   6s

» kubectl create -f deployment.yaml
deployment.apps/my-deployment created

» kubectl get po
NAME                            READY   STATUS         RESTARTS   AGE
my-deployment-f65f874fb-ddfmd   0/1     ErrImagePull   0          19s

» kubectl get pvc
NAME     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
my-pvc   Bound    pvc-4b0acfeb-8e3e-4f7b-9929-1648b4adb969   10Gi       RWO            ibmc-vpc-block-5iops-tier   37s

» kubectl describe pvc my-pvc                                                                                                 1 ↵
Name:          my-pvc
Namespace:     default
StorageClass:  ibmc-vpc-block-5iops-tier
Status:        Bound
Volume:        pvc-4b0acfeb-8e3e-4f7b-9929-1648b4adb969
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       my-deployment-f65f874fb-ddfmd
Events:
  Type    Reason                 Age                   From                                                                                                     Message
  ----    ------                 ----                  ----                                                                                                     -------
  Normal  Provisioning           4m1s                  vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-5955fbbdc8-t5lj2_4a53e1b6-cb7f-427f-93a0-7eb8341d9d52  External provisioner is provisioning volume for claim "default/my-pvc"
  Normal  ExternalProvisioning   3m52s (x2 over 4m1s)  persistentvolume-controller                                                                              waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
  Normal  ProvisioningSucceeded  3m49s                 vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-5955fbbdc8-t5lj2_4a53e1b6-cb7f-427f-93a0-7eb8341d9d52  Successfully provisioned volume pvc-4b0acfeb-8e3e-4f7b-9929-1648b4adb969

» kubectl describe po my-deployment-f65f874fb-ddfmd
Name:             my-deployment-f65f874fb-ddfmd
Namespace:        default
Priority:         0
Service Account:  default
Node:             10.240.128.26/10.240.128.26
Start Time:       Tue, 13 Jun 2023 14:08:01 +0530
Labels:           app=my-app
                  pod-template-hash=f65f874fb
Annotations:      cni.projectcalico.org/containerID: ddacf04cc145a98608d9cc9e50bbf60a92bb50ef6ba8520acf10bac8219430a1
                  cni.projectcalico.org/podIP: 172.22.36.141/32
                  cni.projectcalico.org/podIPs: 172.22.36.141/32
Status:           Pending
IP:               172.22.36.141
IPs:
  IP:           172.22.36.141
Controlled By:  ReplicaSet/my-deployment-f65f874fb
Containers:
  my-container:
    Container ID:
    Image:          ngnix
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mount-path from my-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bwfhp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  my-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-pvc
    ReadOnly:   false
  kube-api-access-bwfhp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 600s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 600s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Normal   Scheduled               4m38s                  default-scheduler        Successfully assigned default/my-deployment-f65f874fb-ddfmd to 10.240.128.26
  Normal   SuccessfulAttachVolume  4m29s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-4b0acfeb-8e3e-4f7b-9929-1648b4adb969"
  Normal   Pulling                 2m49s (x4 over 4m27s)  kubelet                  Pulling image "ngnix"
  Warning  Failed                  2m48s (x4 over 4m26s)  kubelet                  Failed to pull image "ngnix": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/ngnix:latest": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:6e8f42933df9307a519158c9f6167b4693bacc6e1df7464415ae1c9bc6229345: not found
  Warning  Failed                  2m48s (x4 over 4m26s)  kubelet                  Error: ErrImagePull
  Warning  Failed                  2m35s (x6 over 4m26s)  kubelet                  Error: ImagePullBackOff
  Normal   BackOff                 2m24s (x7 over 4m26s)  kubelet                  Back-off pulling image "ngnix"
```

### CODE REVIEW

**Comment by spzala** [comment]
CLA approval in progress. Thanks!

**Review by ambiknai — COMMENTED** [review]
Hi Subash
Thanks for the PR . We had to deliver this fix as part of our new addon version release and this change is already in place.
https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/blob/master/deploy/kubernetes/driver/kubernetes/manifests/controller-server.yaml

**Pull request closed without merging**
