### PR TITLE
Update in deployment files for snapshot support

### PR DESCRIPTION
**Pull request by GunaKKIBM**

### CODE REVIEW

**Review by ambiknai — CHANGES_REQUESTED** [review]
@GunaKKIBM  
We have to add images [here](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/tree/master/deploy/kubernetes/driver/kubernetes/overlays) (all folders)
Please update csi-provisioner image to 3.2.1 version

**Review by meghnasiingh — APPROVED** [review]
LGTM. Just update provisioner version

**Review by ambiknai — APPROVED** [review]

**Review by sameshai — APPROVED** [review]
/lgtm

**Pull request merged**
